development:
  adapter: postgresql
  database: db/naval_db.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: db/production.sqlite3
  pool: 5
  timeout: 5000
